### PR TITLE
Updated

### PR DESCRIPTION
**Pull request by cganote**

### CODE REVIEW

**Comment by nsoranzo** [comment]
I guess this can be closed.

**Comment by bgruening** [comment]
Think so too. @cganote do you want to work on this or can we close this?

**Comment by cganote** [comment]
I don't even remember what it was. Go ahead and close it =)

**Comment by bgruening** [comment]
I can not. @peterjc can!

**Comment by peterjc** [comment]
Thanks for the reminder - something equivalent was included in https://github.com/peterjc/galaxy_blast/commit/adfeb6a86b5712c7f7c92fddbfb76a74764ab3d3 where I was able to use the same server and version of the cdd_delta database, meaning less extra changes in the diff.

Looking back I should probably add Carrie's name to the version history for her part in the updates for BLAST+ 2.2.31 - is that OK with you @cganote?

See https://github.com/peterjc/galaxy_blast/blob/master/tools/ncbi_blast_plus/README.rst

**Comment by cganote** [comment]
Are you speaking of the line that starts with:
These wrappers are copyright 2010-2014

**Comment by peterjc** [comment]
That too, since its 2015, but I mean the entry in the history table for v0.1.06 which just says:

* Now depends on package_blast_plus_2_2_31 in ToolShed.
* Tests updated for BLAST+ 2.2.31 instead of BLAST+ 2.2.30.

@cganote You helped with that update during the Norwich Galaxy Hackathon, and I ought to have put your name against it.

More generally, I've been wondering how best to collate a proper contributors list for the repository as a whole or at least each tool/suite. Perhaps we need a separate GitHub issue to discuss that...

**Comment by cganote** [comment]
Sure, if you think it acknowledgement-worthy. In general I like the practice of putting peoples' github or twitter handles in the commit/pr - is this what you mean?
I'm for devising a system where if someone does something awesome, you buy them a virtual beer. Redeemable for real beer/soda/candy. I'd call it beercoins. =D

**Pull request closed without merging**
