### PR TITLE
Blastcmd adaptability

### PR DESCRIPTION
**Pull request by Frahiriart**
Now with the tool blastdbcmd you can now use a blast database from history as an input of the tool

### CODE REVIEW

**Comment by peterjc** [comment]
Looks like things have moved on since I last did any work on this myself,

```
ERROR: Your Python version is: 2.7.15
Galaxy is currently supported on Python >=3.5 .
To run Galaxy, please install a supported Python version.
If a supported version is already installed but is not your default,
https://docs.galaxyproject.org/en/latest/admin/python.html contains instructions
on how to force Galaxy to use a different version.
```

We should tackle this first, on a separate pull request. It should be fairly straightforward...

**Comment by nsoranzo** [comment]
@peterjc It's actually already taken care of in https://github.com/peterjc/galaxy_blast/pull/127 .

**Comment by Frahiriart** [comment]
So i wait that the pull request  [#123](https://github.com/peterjc/galaxy_blast/pull/123) is added in master branch.

**Comment by peterjc** [comment]
Rebased version on #130, but this will need a bit more test coverage I think...

**Comment by peterjc** [comment]
Replaced by #130 which built on this, thank you.

**Pull request closed without merging**
