### PR TITLE
Move best_hits method to own module, add blast_rph_report.py to only …

### PR DESCRIPTION
**Pull request by tom6931**
These changes move the best_hits method to it's own module (best_hits.py) along with a few variables that the best_hits method needs.  The script blast_rbh.py was modified to use the best_hits module. A new script, blast_rbh_report.py, takes two BLAST tabular files as input and performs the best hits analysis on them.  These changes have been checked against the tests in update_tests.sh.  
TODO: add checking to blast_rbh_report.py that the correct number of columns etc are present in the input tabular files.

### CODE REVIEW

**Comment by peterjc** [comment]
The restructuring seems sensible in principle 👍 

From a code structure point of view, the quick-and-dirty solution of a global for ``tie_warning`` is no longer as appealing. Any suggestions?

Also, rather than making ``min_identity`` and ``min_coverage`` module level parameters, I'd put them as optional arguments to the ``best_hits`` function. Again, this reflects a the short term implementation of the original script.

As to the automated tests, I don't recall turning on Codacy - I'll try to turn that off. However, TravisCI is failing the ``flake8`` style tests. It looks cosmetic in a sense - running the command line tool ``black`` will sort out a lot of it automatically:

```
$ pip install black
$ pip install flake8 flake8-blind-except flake8-docstrings flake8-rst-docstrings restructuredtext-lint
```

I should update the ``CONTRIBUTING`` file on this...

**Comment by tom6931** [comment]
Thanks for the feedback.  I agree that making min_identity and min_coverage option arguments to best_hits is a good idea.

I’m not sure about the tie_warning.  The two options that come to mind are:

  1.  Have it as a return value from best_hits.
  2.  Add a method to the best_hits module to get the value.  This would still leave it as a global variable floating around best_hits.py.
I can check with a developer in my group here who might have an idea.

Codacy actually pointed out a few imported modules that I should have removed but didn’t, so it was actually helpful in that regard.

I’d like to do a new pull request by tomorrow.  I’ll be off Monday through Wednesday and won’t be able to do any work.

Regards,

Tom

Thomas L. Madden, Ph.D.
Staff Scientist
NCBI/NLM/NIH
madden@ncbi.nlm.nih.gov

**Comment by tom6931** [comment]
I looked at the tie_warning situation with Greg Boratyn (developer in the group).  We didn't see any way to get away from the global variable without restructuring a lot of code (and possibly breaking something), so I left it as is.  I did make the changes for min_identity and min_coverage, and I think you (Peter) can see them along with the fixes suggested by Codacy.

**Comment by peterjc** [comment]
I though I turned Codacy off, in any case it is only complaining about assert lines.

**Comment by peterjc** [comment]
Merged, thank you Tom 👍

**Pull request merged**
