### PR TITLE
Wrap NCBI BLAST+ 2.14.1

### PR DESCRIPTION
**Pull request by peterjc**
Would close issue #146 and #156 (but will need the test output etc updated too)

### CODE REVIEW

**Comment by peterjc** [comment]
Looks like a generic failure, not specific to this update. e.g.

```
Job in error state.. tool_id: ncbi_blastx_wrapper, exit_code: 125, stderr: docker: invalid spec: ::rw: empty section between colons.
See 'docker run --help'.
```

That makes this harder...

**Comment by bgruening** [comment]
@peterjc you need to update the CI to point to a recent Galaxy version. Best is to copy latest changes from IUC.

**Comment by peterjc** [comment]
Thanks for the confirmation - that's what I guessed was needed.Message ID:
***@***.***>

>

**Comment by peterjc** [comment]
Rebasing after #158

**Comment by peterjc** [comment]
9 of these ``WARNING: Command template contains TODO text.` from the planemo linting, it has got stricter...

**Comment by bgruening** [comment]
Oh yes, we get stricter and stricter :)

**Comment by peterjc** [comment]
Oops - the updated test files were still using BLAST+ 2.10.1, not 2.14.1. Regenerating now...

**Comment by bgruening** [comment]
Thanks for working on this @peterjc! Very appreciated.

**Comment by peterjc** [comment]
Nearly, something amiss in get_species_taxids:

```
Job in error state.. tool_id: get_species_taxids, exit_code: 1, stderr: id: unknown ID 1001
id: unknown ID 1001
/tmp/tmpqvejknye/job_working_directory/000/25/tool_script.sh: line 23: [: too many arguments
id: unknown ID 1001
id: unknown ID 1001
Taxonomy ID not found
.
```

**Comment by bgruening** [comment]
@peterjc can we help here in any way?

for your information @Deeptivarshney

**Comment by peterjc** [comment]
I'm unsure what is wrong with get_species_taxids (and if it is new or long standing but overlooked). Maybe I should merge this anyway and release it as is (better for most people)?

**Comment by bgruening** [comment]
> I'm unsure what is wrong with get_species_taxids (and if it is new or long standing but overlooked). Maybe I should merge this anyway and release it as is (better for most people)?

> [Well, perhaps comment out this tool for now]

Yes that would be nice :)

**Comment by bgruening** [comment]
Thanks @peterjc. Can you push that manually to the TS please?

**Comment by peterjc** [comment]
As expected the merged commit on the master branch failed in the get_species tests - and thus did not get automatically pushed to the TS.

Main Tool Shed updated.

Test Tool Shed *not* updated. Seems my API key is not valid anymore, might we out of sync with my other machine. I will check later.

**Comment by bgruening** [comment]
Skip the TTS. We updating the TTS at the moment to version 2.0 :scream:

**Comment by peterjc** [comment]
Thanks.

**Pull request merged**
