### PR TITLE
Add `-max_hsps` and `-use_sw_tback` options. Add `argument` attribute

### PR DESCRIPTION
**Pull request by nsoranzo**
Also:
- Move `min` attribute to param
- Remove unused `infile_list` param in `tools/ncbi_blast_plus/ncbi_makeprofiledb.xml`
- Remove useless `conditional`s around select `param`s in ` tools/ncbi_blast_plus/ncbi_psiblast_wrapper.xml`

### CODE REVIEW

**Comment by peterjc** [comment]
You've included various bits of tiding work I was behind on - and support for the argument on the parameters (this will close #68) is also very welcome 🥇 

This looks great - can you also update the ``README.rst`` file ready for a release?

(We don't need need to bump the version number as v0.2.01 is not yet on the main tool shed)

**Comment by nsoranzo** [comment]
> This looks great - can you also update the README.rst file ready for a release?

Will do. Actually I wanted to ask if you can do a release after this is merged :blush: 

One of test jobs is failing due to a temporary link validation issue, can you restart it?

**Comment by peterjc** [comment]
Thank you - time to do a release to the Main Tool Shed this afternoon (after a manual test of the automatic upload to the Test Tool Shed which should be underway now via TravisCI on the master branch).

**Comment by nsoranzo** [comment]
Thanks @peterjc!

**Comment by peterjc** [comment]
Basic checks worked locally - and your eagle eye has made me update the TravisCI setup to enforce no trailing whitespace too 😉

**Comment by peterjc** [comment]
It took me two goes, but I added ``argument=`` to the ``-db`` and ``-subject`` parameters as well, 890dbeb7a06f1a1ca661d69b5440aa375822cf45 and 038641dc56c4f5880eedf536ba8313786c71dc0b

**Comment by peterjc** [comment]
This is now on the tool shed as https://toolshed.g2.bx.psu.edu/view/devteam/ncbi_blast_plus/6f386c5dc4fb from commit 79d887889628556d02f7daad913e60012ad5218b

Already on the test tool shed as https://testtoolshed.g2.bx.psu.edu/view/devteam/ncbi_blast_plus/f85b83203d68

**Comment by nsoranzo** [comment]
Thanks @peterjc!

**Pull request merged**
