### PR TITLE
BLAST+ v2.9.0

### PR DESCRIPTION
**Pull request by peterjc**
Based on commits from #123 by @abretaud rebased onto the master branch.

### CODE REVIEW

**Comment by peterjc** [comment]
Whoops, `test-data/deltablast_four_human_vs_rhodopsin.xml` missing.

**Comment by peterjc** [comment]
@abretaud are you happy to be thanked by name (at the start with the other names, and/or in the change log)?:
https://github.com/peterjc/galaxy_blast/blob/master/tools/ncbi_blast_plus/README.rst

**Comment by abretaud** [comment]
Sure no problem! Thanks for working on this!

**Comment by peterjc** [comment]
Done, thank you.

**Comment by peterjc** [comment]
Tool sheds updated:

https://testtoolshed.g2.bx.psu.edu/view/devteam/ncbi_blast_plus/fa7f92b81db1
https://toolshed.g2.bx.psu.edu/view/devteam/ncbi_blast_plus/6f8ea4b9a2c4

**Pull request merged**
